services:
  gateway:
    image: nginx:alpine
    container_name: events-gateway
    ports:
      - "8217:8080"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - events
      - other
    restart: always

  events:
    build: ./services/events
    image: events-s05:compose
    container_name: events-container
    expose:
      - "8000"
    restart: always

  other:
    build: ./services/other
    image: other-mock:compose
    container_name: other-container
    expose:
      - "8000"
    restart: always
