events {}

http {
    upstream events_backend {
        server events-svc-s05:8217;
    }

    upstream other_backend {
        server other-svc:8217;
    }

    server {
        listen 8080;

        location /api/events {
            proxy_pass http://events_backend;
        }

        location /api/other {
            proxy_pass http://other_backend;
        }
    }
}